version: 2.1

# # Check out orbs later
# orbs:
#   python: circleci/python@0.2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.7.4
    # executor: python/default
    steps:
      - checkout
      # - python/load-cache
      # - python/install-deps
      # - python/save-cache
      - run:
          command: python -m pip install -r requirements.txt --user
          name: Install-deps
      - run:
          # command: python -c "print(\"Some test information\")"
          # command: ./manage.py
          command: ls test*/*
          name: Test
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports

workflows:
  main:
    jobs:
      - build-and-test
